spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

openai.api.key=${OPENAI_API_KEY}

shopify.api.key=${SHOPIFY_API_KEY}
shopify.api.secret=${SHOPIFY_API_SECRET}
shopify.api.version=${SHOPIFY_API_VERSION:2025-07}

shopify.store.domain=${SHOPIFY_STORE_DOMAIN}
shopify.admin.access-token=${SHOPIFY_ADMIN_ACCESS_TOKEN}
shopify.custom.install-url=${SHOPIFY_CUSTOM_INSTALL_URL}